<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.jzy3d</groupId>
	<artifactId>jzy3d-tutorials</artifactId>
	<version>3.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>Jzy3d Tutorials</name>

	<modules>
		<module>jzy3d-tutorials-emul-gl-swing</module>
		<module>jzy3d-tutorials-emul-gl-swt</module>
		<module>jzy3d-tutorials-jogl-swing</module>
		<module>jzy3d-tutorials-jogl-swt</module>
		<module>jzy3d-tutorials-jogl-javafx</module>
		<module>jzy3d-tutorials-jogl-newt</module>
		<module>jzy3d-tutorials-panama-gl-swing</module>
		<module>jzy3d-tutorials-panama-gl-javafx</module>
	</modules>

	<!--To retrieve Jzy3d dependencies -->
	<repositories>

		<repository>
			<id>jzy3d-snapshots</id>
			<name>Jzy3d Snapshots</name>
			<url>https://maven.jzy3d.org/snapshots/</url>
		</repository>

		<repository>
			<id>jzy3d-releases</id>
			<name>Jzy3d Releases</name>
			<url>https://maven.jzy3d.org/releases/</url>
		</repository>

	</repositories>

	<!--To deploy tutorials: 1) this project does not references master to be
		able to be build alone 2) master still reference this project to build it
		with the API involve being deployable by mvn deploy -->
	<distributionManagement>
		<repository>
			<id>jzy3d-ftp-maven</id>
			<name>Jzy3d Maven Folder</name>
			<url>ftp://www.jzy3d.org/v1/maven/releases</url>
		</repository>
		<snapshotRepository>
			<id>jzy3d-ftp-maven</id>
			<name>Jzy3d Maven Folder SNAPSHOTS</name>
			<url>ftp://www.jzy3d.org/v1/maven/snapshots</url>
		</snapshotRepository>
	</distributionManagement>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<version.java>1.8</version.java>
	</properties>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>${version.java}</source>
					<target>${version.java}</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.2.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<phase>verify</phase>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>
