<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0"
	xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.jzy3d</groupId>
		<artifactId>jzy3d-tutorials</artifactId>
		<version>3.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>jzy3d-tutorials-jogl-javafx</artifactId>
	<name>Jzy3d Tutorials - JOGL / JavaFX</name>
	<packaging>pom</packaging>

	<properties>
		<openjfx.version>17</openjfx.version>
	</properties>

	<modules>
		<module>jzy3d-tutorials-jogl-javafx-jdk8</module>
		<module>jzy3d-tutorials-jogl-javafx-jdk17</module>
		<module>jzy3d-tutorials-jogl-javafx-jdk19</module>
	</modules>

</project>
